import { Directive, ElementRef, Renderer2, inject } from '@angular/core';

@Directive({
  selector: 'span, div, li',
})
export class TooltipDirective {
  private readonly element = inject(ElementRef);
  private renderer2 = inject(Renderer2);

  ngOnInit() {
    if (!this.element?.nativeElement) return;
    console.log(this.element);
    this.renderer2.setAttribute(
      this.element.nativeElement,
      'data-cy',
      `AUTOGENERATED-ID_${this.element.nativeElement.id}-NODENAME_${this.element.nativeElement.nodeName}-NODETYPE_${this.element.nativeElement.nodeType}-CLASS_${this.element.nativeElement.className}`
    );
  }
}
