import { Directive, ElementRef, Renderer2, inject } from '@angular/core';

@Directive({
  selector: 'span, div, li',
})
export class TooltipDirective {
  private readonly element = inject(ElementRef);
  private renderer2 = inject(Renderer2);

  ngOnInit() {
    if (!this.element?.nativeElement) return;
    console.log(this.element);
    const el = this.element.nativeElement;
    this.renderer2.setAttribute(
      el,
      'data-cy',
      el.id?.toString()
      || `AUTOGENERATED-NODENAME_${el.nodeName} -LIST_INDEX_${Array.from(el.parentElement?.childNodes).indexOf(el)}-PARENTNAME_${el.parentElement?.localName}-previousElementSiblingNAME_${el.previousElementSibling?.localName}-nextElementSiblingNAME_${el.nextElementSibling?.localName}`
    );
  }
}
